// Auth types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';



//Config types
export const SETLOADERVISIBLE='SETLOADERVISIBLE'
export const SETBOTTOMTABBARVISIBLE='SETBOTTOMTABBARVISIBLE'
export const SCROLLTOPOSITION='SCROLLTOPOSITION'